// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlEmVqcdXxaYx5nZ9-oznS9SBXy1HlQQ4',
    appId: '1:292971925218:web:d2f112a267c2eb94fa98bb',
    messagingSenderId: '292971925218',
    projectId: 'galeria-animales',
    authDomain: 'galeria-animales.firebaseapp.com',
    storageBucket: 'galeria-animales.firebasestorage.app',
    measurementId: 'G-B7KVSBNV22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9FXWNXv82qlzUVqpE3IUKA1o0c6K4ivA',
    appId: '1:292971925218:android:2b9644157631ab07fa98bb',
    messagingSenderId: '292971925218',
    projectId: 'galeria-animales',
    storageBucket: 'galeria-animales.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7DlepQJNC2mq5mWN349ZUKKeAxw0z28U',
    appId: '1:292971925218:ios:0d4af1f0fe04e727fa98bb',
    messagingSenderId: '292971925218',
    projectId: 'galeria-animales',
    storageBucket: 'galeria-animales.firebasestorage.app',
    iosBundleId: 'com.example.app002',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7DlepQJNC2mq5mWN349ZUKKeAxw0z28U',
    appId: '1:292971925218:ios:0d4af1f0fe04e727fa98bb',
    messagingSenderId: '292971925218',
    projectId: 'galeria-animales',
    storageBucket: 'galeria-animales.firebasestorage.app',
    iosBundleId: 'com.example.app002',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlEmVqcdXxaYx5nZ9-oznS9SBXy1HlQQ4',
    appId: '1:292971925218:web:53d7e97d9461a31bfa98bb',
    messagingSenderId: '292971925218',
    projectId: 'galeria-animales',
    authDomain: 'galeria-animales.firebaseapp.com',
    storageBucket: 'galeria-animales.firebasestorage.app',
    measurementId: 'G-JL2W25TBH4',
  );
}
